export const PRICE = '£15'
export const HEADING = 'Request an additional black bin'
export const WhatYouCanPutInYourBinsLink = 'https://www.stockport.gov.uk/what-you-can-put-in-your-bins'
export const OrderRecyclingBinsLink = 'https://www.stockport.gov.uk/start/additional-recycling-bins'
export const  PDFLink = 'https://s3-eu-west-1.amazonaws.com/live-iag-static-assets/pdf/BinCalendars/Waste+diary+v2.pdf'
export const  PDFSize = '74Kb'